name: Dependabot[bot]

on: [workflow_call, pull_request_target]

jobs:
  dependabot:
    name: Dependabot[bot]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: Generate Access Token
        id: auth
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.KDEVBOT_APPID }}
          private-key: ${{ secrets.KDEVBOT_PRIVATE_KEY }}

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Approve Pull Request
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ steps.auth.outputs.token }}
          PR: ${{ github.event.pull_request.number }}
        run: gh pr review $PR --approve

      - name: Lock Pull Request
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ steps.auth.outputs.token }}
          PR: ${{ github.event.pull_request.number }}
        run: gh pr lock $PR