# Copyright (C) 2024 Katsute <https://github.com/Katsute>

name: Deploy

on:
  workflow_call:
    inputs:
      node-version:
        type: number
        default: 20
        required: false

      environment:
        type: string
        required: false

jobs:
  Deploy:
    name: Deploy (Node ${{ inputs.node-version }})
    runs-on: windows-latest
    timeout-minutes: 60
    environment: ${{ inputs.environment }}
    if: github.repository_owner == 'KatsuteDev'
    steps:
      - name: Generate Access Token
        id: auth
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.KDEVBOT_APP_ID }}
          private-key: ${{ secrets.KDEVBOT_PRIVATE_KEY }}

      - name: Checkout Repository
        uses: actions/checkout@v4

        # https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md#:~:text=WiX%20Toolset
      - name: Add WiX Toolset to Path
        run: echo "C:\Program Files (x86)\WiX Toolset v3.11\bin" >> $GITHUB_PATH
        shell: bash

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          architecture: x64
          cache: npm
          node-version: ${{ inputs.node-version }}

      - name: Build
        run: npm i

      - name: Rebuild
        run: npm run rebuild --if-present

      - name: Package Executable
        run: npm run make

      - name: Deploy to Releases
        uses: AButler/upload-release-assets@v3.0
        with:
          files: 'out/make/**/*.exe;out/make/**/*.msi;out/make/**/*.zip'
          repo-token: ${{ steps.auth.outputs.token }}