# Copyright (C) 2024 Katsute <https://github.com/Katsute>

name: Stale

on: [workflow_call]

jobs:
  stale:
    name: Stale
    runs-on: ubuntu-latest
    if: >-
      github.repository_owner == 'KatsuteDev' &&
      github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
    steps:
      - name: Generate Access Token
        id: auth
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.KDEVBOT_APP_ID }}
          private-key: ${{ secrets.KDEVBOT_PRIVATE_KEY }}

      - uses: actions/stale@v9
        with:
          repo-token: ${{ steps.auth.outputs.token }}
          days-before-stale: 14
          days-before-close: 7
          stale-issue-message: >-
            This issue has been marked as stale due to inactivity.
          stale-pr-message: >-
            This pull request has been marked as stale due to inactivity.
          close-issue-message: >-
            This issue has been closed due to inactivity.
          close-pr-message: >-
            This pull request has been closed due to inactivity.
          stale-issue-label: stale
          stale-pr-label: stale
          operations-per-run: 100
          exempt-all-milestones: true
          exempt-all-assignees: true

  lock:
    name: Lock Stale Issues
    runs-on: ubuntu-latest
    if: >-
      github.repository_owner == 'KatsuteDev' &&
      (github.event_name == 'issues' && contains(github.event.issue.labels.*.name, 'stale')) ||
      (github.event_name == 'pull_request' && contains( github.event.pull_request.labels.*.name, 'stale'))
    steps:
      - name: Generate Access Token
        id: auth
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.KDEVBOT_APP_ID }}
          private-key: ${{ secrets.KDEVBOT_PRIVATE_KEY }}

      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          token: ${{ steps.auth.outputs.token }}

      - name: Issue Lock
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ steps.auth.outputs.token }}
          ISSUE: ${{ github.event.issue && 'issue' || 'pr' }}
          NUMBER: ${{ github.event.issue && github.event.issue.number || github.event.pull_request.number }}
        run: gh $ISSUE lock $NUMBER